name: APIsec

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '34 1 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: APIsec scan
        uses: apisec-inc/apisec-run-scan@v1
        with:
          apisec-username: ${{ secrets.APISEC_USERNAME }}
          apisec-password: ${{ secrets.APISEC_PASSWORD }}
          apisec-project: "VAmPI"
          sarif-result-file: "apisec-results.sarif"

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: sarif-results
          path: apisec-results.sarif

  upload-results:
    needs: scan
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download SARIF artifact
        uses: actions/download-artifact@v4
        with:
          name: sarif-results

      - name: Import results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: apisec-results.sarif
